name: 'Allure report simple'
description: 'Generate Allure report for test suite'
branding:
  icon: 'check-square'
  color: 'purple'
inputs:
  results-dir:
    description: 'Allure test result data dir'
    required: true
    default: 'allure-results'
  report-dir:
    description: 'Allure report target dir'
    required: true
    default: 'allure-report'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.results-dir }}
    - ${{ inputs.report-dir }}
